import { Product } from "../types/takeaway";

export const SAMPLE_PRODUCTS: Product[] = [
  {
    id: "00000000-0000-0000-0000-000000000001",
    name: { en: "Hummus", fr: "Houmous", nl: "Hummus" },
    description: {
      en: "Chickpeas puree with tahini (sesame paste)",
      fr: "Purée de pois chiches au tahini (pâte de sésame)",
      nl: "Kikkererwten puree met tahini (sesampasta)",
    },
    price: 7.5,
    category: "cold-mezzes",
    image_url: "/images/cold-mezzes/houmos.webp",
    available: true,
    sort_order: 1,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: "00000000-0000-0000-0000-000000000002",
    name: { en: "Moutabal", fr: "Moutabal", nl: "Moutabal" },
    description: {
      en: "Grilled eggplant caviar with tahini (sesame paste)",
      fr: "Caviar d'aubergine grillée au tahini (pâte de sésame)",
      nl: "Gegrilde aubergine kaviaar met tahini (sesampasta)",
    },
    price: 8.0,
    category: "cold-mezzes",
    image_url: "/images/cold-mezzes/moutabal.webp",
    available: true,
    sort_order: 2,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: "00000000-0000-0000-0000-000000000003",
    name: { en: "Falafel", fr: "Falafel", nl: "Falafel" },
    description: {
      en: "Deep-fried mashed chickpea balls served with tahini sauce",
      fr: "Boulettes de pois chiches frits servies avec sauce tahini",
      nl: "Gefrituurde kikkererwten balletjes geserveerd met tahini saus",
    },
    price: 7.0,
    category: "hot-mezzes",
    image_url: "/images/hot-mezzes/falafel.webp",
    available: true,
    sort_order: 3,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: "00000000-0000-0000-0000-000000000004",
    name: { en: "Fattoush Salad", fr: "Salade Fattoush", nl: "Fattoush Salade" },
    description: {
      en: "Tomatoes, lettuce, radish, cucumber, onion, fried bread with pomegranate molasses",
      fr: "Tomates, laitue, radis, concombre, oignon, pain frit aux mélasses de grenade",
      nl: "Tomaten, sla, radijs, komkommer, ui, gebakken brood met granaatappel melasse",
    },
    price: 12.0,
    category: "salads",
    image_url: "/images/gallery2/mezze-libanais-restaurant-libanais.webp",
    available: true,
    sort_order: 4,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: "00000000-0000-0000-0000-000000000005",
    name: { en: "Falafel Sandwich", fr: "Sandwich Falafel", nl: "Falafel Sandwich" },
    description: {
      en: "Fresh pita bread filled with falafel, vegetables and tahini sauce",
      fr: "Pain pita frais garni de falafel, légumes et sauce tahini",
      nl: "Vers pitabrood gevuld met falafel, groenten en tahini saus",
    },
    price: 9.5,
    category: "sandwiches",
    image_url: "/images/hot-mezzes/falafel.webp",
    available: true,
    sort_order: 5,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: "00000000-0000-0000-0000-000000000006",
    name: { en: "Shish Taouk", fr: "Shish Taouk", nl: "Shish Taouk" },
    description: {
      en: "Grilled chicken cubes with rice and grilled vegetables",
      fr: "Cubes de poulet grillés avec riz et légumes grillés",
      nl: "Gegrilde kip blokjes met rijst en gegrilde groenten",
    },
    price: 16.5,
    category: "lunch-dishes",
    image_url: "/images/lunch-dishes/shish-taouk.webp",
    available: true,
    sort_order: 6,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: "00000000-0000-0000-0000-000000000007",
    name: { en: "Aish el Saraya", fr: "Aish el Saraya", nl: "Aish el Saraya" },
    description: {
      en: "Sweetened biscuit, vegan pudding, orange blossom water and pistachio",
      fr: "Biscuit sucré, pudding végétalien, eau de fleur d'oranger et pistache",
      nl: "Gezoete biscuit, veganistische pudding, oranjebloesemwater en pistache",
    },
    price: 8.5,
    category: "desserts",
    image_url: "/images/desserts/aish-el-saraya.webp",
    available: true,
    sort_order: 7,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
];


